version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: hotelBookingSystem-postgres
    environment:
      POSTGRES_DB: hotelBookingSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
