spring:
    application:
        name: hotelBookingSystem
    datasource:
        url: jdbc:postgresql://localhost:5432/hotelBookingSystem
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:/db.changelog/changelog-master.xml



